version: "3.9"

services:
  db:
    image: mysql:8
    container_name: paekom-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    build: .
    container_name: paekom-ai
    env_file:
      - .env
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app # 로컬 app 폴더 → 컨테이너 /app/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  db_data:
